<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
</div>

<img src="media/ensmp-25-alpha.png" />

In [1]:
import numpy as np

# algèbre linéaire

Un des premières utilisations de la librarie `numpy` sera faite dans le cadre des cours de mathématiques et de la manipulation de matrices.

Aussi allons-nous voir dans ce notebook les quelques fonctions d'algèbre linéaire qui vont vous être utiles, naturellement il vous faudra vous référer au site de Python-scientifique pour chercher des fonctions plus avancées.

Il faut savoir que les fonctions d'algèbre linéaire des libraries `np.linalg` sont tout particulièrement efficaces et ce pour plusieurs raisons:
   1. déjà ces fontions s'appuient sur les algorithmes efficaces 
   1. ensuite ces fonctions sont codées dans des langages de *bas niveau* très proches de la mémoire donc rapides
   1. enfin les implémentations tirent parti du multithreading (où un programme est découpé en sous-programmes s'exécutant *en même temps*) qui permet de grandement améliorer les temps de calculs.

Il existe des différences entre les fonctions de `numpy` et de `scipy` mais nous n'en dirons pas plus référez vous aux explications des concepteurs de ces librairies comme là  https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [2]:
import numpy as np

La première chose à savoir c'est que naturellement les fonctions `numpy` vont s'appliquer sur des tableaux de dimensions supérieures à 2 mais, nous n'allons voir ici, que les vecteurs et matrices donc rester en dimension < à 3.

Nous n'avons vu pour l'instant que des opérations élément par élément. Comme par exemple le `np.mult` ou encore `*`, qui est le *produit matriciel de Hadamard*. Voyons maintenant les fonctions dédiées à l'algèbre linéaire.

## application linéaire

On va se mettre d'accord sur matrice, vecteur et produit en `numpy`.

Attention, comme les matrices et les vecteurs seront des `np.ndarray`, il faudra naturellement faire attention au type des éléments, lors d'éventuelles modifications. Si on tente de modifier un élément d'une matrice de type entier avec un nombre flottant, celui-ci sera tronqué et transformé en entier: vous perdrez de l'information.

### la matrice

Une matrice $A$ de dimension $m$ lignes et $n$ colonnes, qui représente une application linéaire $f$ d'un espace de dimension $n$ vers un espace de dimension $m$, est un `np.ndarray` de forme $(m, n)$.

Voila un exemple d'une matrice $A$ de dimension $(2 \times 3)$

In [3]:
A = np.array([[2, 3, -7], [6, -4, 5]])
A

array([[ 2,  3, -7],
       [ 6, -4,  5]])

### le vecteur

Un vecteur $V$ de taille $n$, qui représente un vecteur d'un espace vectoriel de dimension $n$, est un `np.ndarray` de forme $(n,)$.

Voila un exemple de vecteur $V$ de dimension $(3,)$

In [4]:
V = np.array([1, -3, 8])
V

array([ 1, -3,  8])

Attention les `numpy.ndarray` suivant ne sont pas des vecteurs mais des matrices. Il y a bien deux dimensions.

In [5]:
np.array([[100, 200, 300]]).shape

(1, 3)

In [6]:
np.array([[100], [200], [300]]).shape

(3, 1)

Celui là est un vecteur au sens de l'UE11.

In [7]:
np.array([100, 200, 300]).shape

(3,)

### le produit d'une matrice et d'un vecteur

Le produit $A \cdot V$ représente $f(V)$.

Quel est en `numpy` le produit qu'on appelle ici $\times$ ? C'est la fonction `np.dot` (ou encore la méthode `np.ndarray.dot`).

Calculons $A \cdot V$

In [8]:
# la fonction
np.dot(A, V)

array([-63,  58])

In [9]:
# la méthode
A.dot(V)

array([-63,  58])

### le produit de deux matrices

Maintenant prenons $A$ et $B$, deux matrices représentant respectivement les applications linéaires $f$ et $g$, le produit de matrices $A \cdot B$ est la composition des applications $ƒ ￮ g$.

$A$ on l'a déjà, prenons $B$

In [10]:
B = np.array([[-5, 4], [3, 9], [-4, 2]])
B

array([[-5,  4],
       [ 3,  9],
       [-4,  2]])

In [11]:
np.dot(A, B)

array([[ 27,  21],
       [-62,  -2]])

In [12]:
A.dot(B)

array([[ 27,  21],
       [-62,  -2]])

### raccourci  *@* pour le produit matriciel

Il s'avère que `numpy` possède un fonction `np.matmul` (qui en dimension 2 est à peu près équivalente à `np.dot`) et qui s'écrit aussi sous la forme *@*

In [13]:
np.matmul(A, B)

array([[ 27,  21],
       [-62,  -2]])

In [14]:
A @ B

array([[ 27,  21],
       [-62,  -2]])

Il existe des différences entre `np.matmul` et `np.dot`  tout d'abord , la multiplication par un scalaire n'est possible qu'avec `np.dot` mais surtout en dimensions supérieure à 2 leur comportement diffère complètement.

Préférer utiliser `np.dot` (ou demandez à votre professeur de math).

## le produit scalaire

Si on applique le produit `np.dot` à deux vecteurs on en obtient le produit scalaire.

In [15]:
V1 = np.array([1, -3, 8])
V1

array([ 1, -3,  8])

In [16]:
V2 = np.array([-6, 4, -7])
V2

array([-6,  4, -7])

In [17]:
np.dot(V1, V2)

-74

## la norme de vecteur

Pour un vecteur $V1 =[v_1, ..., v_n]$, , la norme `np.linalg.norm` sera la racine carré du produit scalaire par lui-même $\displaystyle \left\|{ {V}}\right\|_{2}={\sqrt {v_{1}^{2}+\cdots +v_{n}^{2}}}$

In [18]:
# la fonction idoine
np.linalg.norm(V1)

8.602325267042627

In [19]:
# qu'on peut naturellement paraphraser en
np.sqrt(V1.dot(V1))

8.602325267042627

Pour les autres normes de matrices et vecteurs regardez là https://np.org/doc/stable/reference/generated/np.linalg.norm.html#np.linalg.norm

## la transposée d'une matrice

C'est la fonction `np.transpose`. Elle a une version courte `.T` pour écrire des codes plus lisibles.

In [20]:
A = np.arange(1, 13).reshape(4, 3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np.transpose(A)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [22]:
A.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## les matrices identité

En `numpy` la fonction porte le très joli nom de `eye` (parce que *eye* et *I* se prononcent pareil), elle renvoie des matrices de type flottant.

In [23]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## le déterminant d'une matrice

Il est donné par la fonction `np.linalg.det`

In [24]:
A = 2*np.eye(3)
A

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [25]:
np.linalg.det(A)

7.999999999999998

Essayez de l'appliquer à une matrice qui n'est pas carrée ? Vous allez recevoir une `np.linalg.LinAlgError` !

In [26]:
B = np.random.random(size=(3, 4))*10
try:
    np.linalg.det(B)
except np.linalg.LinAlgError as e:
    print(f'Oups pas bon ! ou en mieux dit "{e}"')

Oups pas bon ! ou en mieux dit "Last 2 dimensions of the array must be square"


A vous de jouer. Faites une isométrie (une transformation qui conserve les longueurs) et calculez son déterminant.

In [27]:
# votre code ici (une solution dessous)

In [28]:
M = np.array([[0, -1], [1, 0]])
print(M)
np.linalg.det(M)

[[ 0 -1]
 [ 1  0]]


1.0

In [29]:
# une isométrie
M = np.array([[0, -1], [1, 0]])
print(M)
np.linalg.det(M)

[[ 0 -1]
 [ 1  0]]


1.0

## les matrices diagonales

On peut créer une matrice diagonale à partir de la liste des éléments de sa diagonale

In [30]:
np.diag([1., 2, 3])

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

On peut aussi extraire la matrice diagonale d'une matrice.

In [31]:
A = np.random.randint(-100, +100, size=(3, 3))
A

array([[-19,  58,   1],
       [-57, -52,  65],
       [-84,  83, -21]])

In [32]:
# returns the diagonal of b
np.diag(A) 

array([-19, -52, -21])

In [33]:
# creates a diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## la trace d'une matrice

C'est la somme des éléments de sa diagonale.

In [34]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.trace(A)

30

In [36]:
np.sum(np.diag(A))

30

## l'inversion d'une matrice

c'est le calcul de $A^{-1}$

In [37]:
# prenons une rotation
R = np.array([0, 1, 0, 0, 0, 1, 1, 0, 0]).reshape(3, 3)
R

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [38]:
# pour calculer son inverse
np.linalg.inv(R)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

pour nous convaincre que ça fonctionne comme attendu :  
lorsqu'en maths on écrit $A^{-1}A = I$, en informatique c'est $A^{-1}A \approx I$ (presque égal à cause des approximations)  

c'est l'intérêt de `np.close` que de comparer si deux tableaux sont presque identiques

In [39]:
# on prend maintenant une matrice quelconque
n = 3
A = np.random.random(size=(n, n))
A

array([[0.93373119, 0.10523338, 0.87603714],
       [0.49950209, 0.36287213, 0.33904144],
       [0.61549253, 0.16558198, 0.41256615]])

In [40]:
# son inverse
Ainv = np.linalg.inv(A)

Vérifions que leur produit fait bien l'identité

In [41]:
np.dot(Ainv, A) == np.eye(n)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

Et bien oui on a des valeurs approchées.

In [42]:
np.isclose(  Ainv @ A,  np.eye(n))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## les valeurs propres d'une matrice (eigen values)

On va calculer les $v$ tels que:
   - $f(v) = \lambda v$ 
   - $M \cdot v = \lambda v$

In [43]:
M = np.random.random(size=(3, 3))
M

array([[0.90883611, 0.21673222, 0.05352073],
       [0.35403477, 0.19018926, 0.92288848],
       [0.83103052, 0.18245235, 0.80158241]])

In [44]:
ls, vs = np.linalg.eig(M)  # eigen_values, eigen_vectors
ls, vs

(array([1.39735699, 0.29976419, 0.20348659]),
 array([[ 0.35556501,  0.34410149,  0.30018621],
        [ 0.63124008, -0.90779779, -0.94514836],
        [ 0.68928186, -0.23978603, -0.12877429]]))

Vérifions qu'on a bien $M \cdot v = \lambda v$

Attention les vecteurs propres sont dans une matrice (3, 3) et chacun d'eux est une des 3 colonnes de la matrice.

In [45]:
# le premier vecteur propre
v0 = vs[:, 0] # toutes les lignes et la colonne 0
# la première valeur propre
l0 = ls[0]
np.all(np.isclose(np.dot(M, v0),  l0*v0))

True

À vous de jouer, à l'aide d'une boucle for-Python, parcourez les valeurs et les vecteurs propres de $M$ et vérifiez $M \cdot v = \lambda v$.

In [46]:
# votre code ici

Prenons la symétrie x↔︎y et calculons ses valeurs et vecteurs propres.

In [47]:
S = np.array([[0, 1], [1, 0]])
values, vectors = np.linalg.eig(S)

print(values)

# les vecteurs sont normés, naturellement
print(vectors)

[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## résolution d'un système linéaire

On va trouver les racines du système linéaire $A \cdot x = b$

Prenons une matrice $A$.

In [48]:
A = np.random.random(size=(3, 3))
A

array([[0.35244108, 0.57865216, 0.39428728],
       [0.74993315, 0.58481961, 0.26170331],
       [0.03769719, 0.55532896, 0.32309592]])

Prenons un vecteur $b$.

In [49]:
b = np.array([1, 2, 3])

Calculons la racine de l'équation $A \cdot x = b$

In [50]:
np.linalg.solve?

In [51]:
x = np.linalg.solve(A, b)
x

array([ -3.56816561,  15.82819328, -17.50360792])

In [52]:
np.all( np.isclose( np.dot(A, x), b) )

True

Si la matrice n'est pas inversible ou si elle n'est pas carrée, une erreur `np.linalg.LinAlgError` sera levée

## les fonctions dont nous avons parlé (rapidement)

| fonctions           |   comportement |
|-----------------|--------|
| `np.dot` | produit de matrice |
| `np.linalg.norm` | normes de matrice |
| `np.transpose` | transposition de matrice |
| `np.linalg.det` | déterminant |
| `np.linalg.inv` | inversion |
| `np.linalg.eig` | valeurs propres |
| `np.linalg.solve` | résolution de système linéaire |
| `np.eye`       |matrice identité  |
| `np.diag`      | matrice diagonale|

Les exercices intéressants seront faits dans l'UE11.

## exercices

### construire une matrice diagonale à-la-main (peu d'intérêt)

On vous demande d'écrire une fonction `matdiag` qui 

1. accepte un paramètre qui est une liste de flottants [$x_1$, $x_2$, …, $x_n$] 
1. retourne une matrice carrée diagonale dont les éléments valent

$$
m_{ii} = x_i 
$$
$$
m_{ij} = 0 \ pour\  i ≠ j
$$
* Retournez toujours un tableau de type `float64`
* Programmez une approche naïve et une approche à base de slicing.

https://nbhosting.inria.fr/auditor/notebook/python-mooc:exos/w7/w7-s05-x5-matdiag

### remplir une matrice : m(i, j) = xi * xj

On vous demande d'écrire une fonction qui 

1. accepte un nombre quelconque de paramètres, $x_1$, $x_2$, ..., $x_n$, tous des flottants
1. retourne une matrice carrée symétrique $M$ dont les termes valent

$$
m_{ij} = x_i . x_j
$$

Indices. Vous pouvez utiliser l'opérateur `@`, la méthode `array.dot()`, le broadcasting, la transposée d'une matrice `.T`.

https://nbhosting.inria.fr/auditor/notebook/python-mooc:exos/w7/w7-s05-x6-xixj